//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boek
    {
        public Boek()
        {
            this.Cursussen = new HashSet<Cursus>();
        }
    
        public int BoekNr { get; set; }
        public string ISBNNr { get; set; }
        public string Titel { get; set; }
    
        public virtual ICollection<Cursus> Cursussen { get; set; }
    }
}
